{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "openaleph.fullname" . }}-secrets
  labels:
    {{- include "openaleph.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  target:
    name: {{ include "openaleph.fullname" . }}-secrets
    creationPolicy: Owner
    template:
      metadata:
        labels:
          {{- include "openaleph.labels" . | nindent 10 }}
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
  data:
    {{- range $key, $val := .Values.externalSecrets.data }}
    - secretKey: {{ $val }}
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ $.Values.externalSecrets.remoteKey | quote }}
        metadataPolicy: None
        property: {{ $key }}
    {{- end }}
{{- end }}
