{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openaleph.serviceAccountName" . }}
  labels:
    {{- include "openaleph.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
