{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openaleph.fullname" . }}-api
  labels:
    {{- include "openaleph.labels" . | nindent 4 }}
    {{- include "openaleph.componentLabels" (dict "component" "api") | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.global.prometheus.enabled }}
    - port: {{ .Values.global.prometheus.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "openaleph.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}
---
{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openaleph.fullname" . }}-ui
  labels:
    {{- include "openaleph.labels" . | nindent 4 }}
    {{- include "openaleph.componentLabels" (dict "component" "ui") | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openaleph.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
{{- end }}
